-- ==============================================================================
-- ARTS (Audit Recommendation Tracking System) - COMPLETE SETUP SCRIPT
-- ==============================================================================
-- Ce script initialise la base de données, crée les tables et insère des données de test.

-- 1. NETTOYAGE (DROP EXISTING TABLES)
-- ==============================================================================
DROP TABLE IF EXISTS audit_logs CASCADE;
DROP TABLE IF EXISTS evidence_submissions CASCADE;
DROP TABLE IF EXISTS action_plans CASCADE;
DROP TABLE IF EXISTS audit_recommendations CASCADE;
DROP TABLE IF EXISTS profiles CASCADE;
DROP TABLE IF EXISTS departments CASCADE;

-- Suppression des types s'ils existent
DROP TYPE IF EXISTS implementation_status CASCADE;
DROP TYPE IF EXISTS audit_type CASCADE;
DROP TYPE IF EXISTS user_role CASCADE;

-- 2. CRÉATION DES TYPES (ENUMS)
-- ==============================================================================
[cite_start]-- Statuts avec code couleur implicite [cite: 68-73]
CREATE TYPE implementation_status AS ENUM (
  'not_implemented',           -- Rouge
  'partially_implemented',     -- Jaune
  'fully_implemented',         -- Vert
  'beyond_management_control', -- Violet
  'not_applicable'             -- Bleu
);

[cite_start]-- Catégories d'audit [cite: 42-46]
CREATE TYPE audit_type AS ENUM (
    'internal_audit', 
    'external_audit', 
    'qms_internal', 
    'qms_external'
);

[cite_start]-- Rôles utilisateurs [cite: 77-83]
CREATE TYPE user_role AS ENUM (
    'admin', 
    'auditor', 
    'focal_person', 
    'director_qms', 
    'staff'
);

-- 3. CRÉATION DES TABLES
-- ==============================================================================

[cite_start]-- TABLE: Départements [cite: 10-32]
CREATE TABLE departments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  acronym TEXT,
  is_active BOOLEAN DEFAULT true
);

-- TABLE: Profils Utilisateurs
-- Note: On ne met pas la Foreign Key vers auth.users tout de suite pour permettre le Seed
CREATE TABLE profiles (
  id UUID PRIMARY KEY, -- Sera lié à auth.users plus tard
  full_name TEXT,
  role user_role DEFAULT 'staff',
  department_id BIGINT REFERENCES departments(id),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

[cite_start]-- TABLE: Recommandations d'Audit [cite: 54-64]
CREATE TABLE audit_recommendations (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  reference_id TEXT UNIQUE NOT NULL, -- ex: AUD-2025-001
  
  -- Détails
  audit_category audit_type NOT NULL,
  report_title TEXT NOT NULL,
  finding_title TEXT NOT NULL,
  description TEXT,
  recommendation_text TEXT NOT NULL,
  
  -- Responsabilités
  responsible_department_id BIGINT REFERENCES departments(id),
  auditor_in_charge_id UUID REFERENCES profiles(id),
  focal_person_id UUID REFERENCES profiles(id),
  
  -- Suivi
  deadline DATE NOT NULL,
  current_status implementation_status DEFAULT 'not_implemented',
  
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

[cite_start]-- TABLE: Plans d'action (Activités) [cite: 58]
CREATE TABLE action_plans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recommendation_id UUID REFERENCES audit_recommendations(id) ON DELETE CASCADE,
  activity_description TEXT NOT NULL,
  assigned_staff_id UUID REFERENCES profiles(id),
  is_completed BOOLEAN DEFAULT false,
  due_date DATE
);

[cite_start]-- TABLE: Preuves (Evidence) [cite: 63]
CREATE TABLE evidence_submissions (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  recommendation_id UUID REFERENCES audit_recommendations(id),
  uploaded_by UUID REFERENCES profiles(id),
  file_url TEXT NOT NULL,
  description_comment TEXT,
  submitted_at TIMESTAMPTZ DEFAULT NOW(),
  auditor_validation_status TEXT DEFAULT 'pending' -- pending, rejected, accepted
);

[cite_start]-- TABLE: Logs d'Audit (Audit Trail) [cite: 99]
CREATE TABLE audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recommendation_id UUID REFERENCES audit_recommendations(id),
  changed_by UUID REFERENCES profiles(id),
  previous_status implementation_status,
  new_status implementation_status,
  change_description TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. INSERTION DES DONNÉES DE TEST (SEED)
-- ==============================================================================

-- A. Départements
INSERT INTO departments (id, name, acronym) VALUES
(1, 'Information Technology & Digital Transformation Department', 'ITDTD'),
(2, 'Domestic Taxes Department', 'DTD'),
(3, 'Customs Services Department', 'CSD'),
(4, 'Finance Department', 'FIND'),
(5, 'Internal Audit and Integrity Department', 'IAID'),
(6, 'Legal Services and Board Affairs Department', 'LSBAD');

-- B. Utilisateurs Fictifs (Pour la démo)
-- Note: Ces utilisateurs ne peuvent pas se connecter (pas de mot de passe).
-- Il faut créer un vrai compte et modifier son rôle ensuite.
DO $$
DECLARE
    id_admin_auditor UUID := 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11';
    id_focal_it UUID := 'b0eebc99-9c0b-4ef8-bb6d-6bb9bd380b22';
    id_focal_tax UUID := 'c0eebc99-9c0b-4ef8-bb6d-6bb9bd380c33';
BEGIN
    INSERT INTO profiles (id, full_name, role, department_id) VALUES
    (id_admin_auditor, 'Gapita Mberabagabo Axel (Demo)', 'auditor', 5),
    (id_focal_it, 'Jean-Claude IT Manager (Demo)', 'focal_person', 1),
    (id_focal_tax, 'Marie-Claire Tax Head (Demo)', 'focal_person', 2);

    -- C. Recommandations
    
    -- 1. Rouge (Not Implemented)
    INSERT INTO audit_recommendations (
        id, reference_id, audit_category, report_title, finding_title, 
        description, recommendation_text, responsible_department_id, 
        auditor_in_charge_id, focal_person_id, deadline, current_status
    ) VALUES (
        '11111111-1111-1111-1111-111111111111', 'AUD-IT-001', 'internal_audit',
        'IT Security Review', 'No MFA on VPN', 
        'VPN relies only on passwords.', 'Implement MFA immediately.',
        1, id_admin_auditor, id_focal_it, CURRENT_DATE + INTERVAL '30 days', 'not_implemented'
    );

    -- 2. Jaune (Partially Implemented)
    INSERT INTO audit_recommendations (
        id, reference_id, audit_category, report_title, finding_title, 
        description, recommendation_text, responsible_department_id, 
        auditor_in_charge_id, focal_person_id, deadline, current_status
    ) VALUES (
        '22222222-2222-2222-2222-222222222222', 'AUD-TAX-089', 'external_audit',
        'Tax Collection Report', 'Slow VAT Refunds', 
        'Refunds take > 30 days.', 'Automate approvals.',
        2, id_admin_auditor, id_focal_tax, CURRENT_DATE - INTERVAL '5 days', 'partially_implemented'
    );

    -- 3. Vert (Fully Implemented)
    INSERT INTO audit_recommendations (
        id, reference_id, audit_category, report_title, finding_title, 
        description, recommendation_text, responsible_department_id, 
        auditor_in_charge_id, focal_person_id, deadline, current_status
    ) VALUES (
        '33333333-3333-3333-3333-333333333333', 'QMS-003', 'qms_internal',
        'ISO 9001 Check', 'Outdated Manuals', 
        'Old SOPs in use.', 'Update all SOPs.',
        3, id_admin_auditor, NULL, CURRENT_DATE - INTERVAL '10 days', 'fully_implemented'
    );
END $$;

-- 5. FINALISATION
-- ==============================================================================
-- On réactive la sécurité pour que les futurs utilisateurs doivent venir de auth.users
-- (Commenté pour éviter des erreurs lors du premier run si auth.users est vide, 
-- mais recommandé pour la prod)
-- ALTER TABLE profiles ADD CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id);